In [1]:
# business question 5Q
# 1 - what months/days have the highest crime rate 
# 2 - what area have most (thieft, BURGLARY, MOTOR VEHICLE THEFT, ROBBERY)  THEFT and check if it domestic 
# 3 - dose area that have more NARCOTICS cases tend to have more OFFENSE INVOLVING CHILDREN 
# 4 - OFFENSE INVOLVING CHILDREN are most of it domestic ? 
# 5 - CRIMINAL DAMAGE rate TO VEHICLE and proprety  
# 6 - what month the looting increased

In [217]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)


%matplotlib inline

In [218]:
def get_dataset(data, limit=200000):
            from sodapy import Socrata

            # in place of application token, and no username or password:
            client = Socrata("data.austintexas.gov", None)


            results = client.get(data, limit=200000)

            # Convert to pandas DataFrame
            results_df = pd.DataFrame.from_records(results)
            results_df.to_csv(f"{data}.csv")

```python
get data  2015 to 2018 
```

```python
get_dataset("spbg-9v94") # 2015 

get_dataset("8iue-zpf6") # 2016 

get_dataset("3t4q-mqs5") # 2017 

get_dataset("pgvh-cpyq") # 2018 
```

In [219]:
df_2015 = pd.read_csv("2015.csv")
df_2016 = pd.read_csv("2016.csv")
df_2017 = pd.read_csv("2017.csv")
df_2018 = pd.read_csv("2018.csv")

In [220]:
df_2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38573 entries, 0 to 38572
Data columns (total 14 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Unnamed: 0                             38573 non-null  int64
 1   go_primary_key                         38573 non-null  int64
 2   council_district                       38401 non-null  float64
 3   go_highest_offense_desc                38573 non-null  object
 4   highest_nibrs_ucr_offense_description  38573 non-null  object
 5   go_report_date                         38573 non-null  object
 6   go_location                            38092 non-null  object
 7   clearance_status                       36649 non-null  object
 8   clearance_date                         36649 non-null  object
 9   go_district                            38573 non-null  object
 10  go_location_zip                        38414 non-null  float64
 11  go_census_tract                        38414 non-null  float64
 12  go_x_coordinate                        37981 non-null  float64
 13  go_y_coordinate                        37981 non-null  float64
dtypes: float64(5), int64(2), object(7)
memory usage: 3.1+ MB

In [221]:
df_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37461 entries, 0 to 37460
Data columns (total 14 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Unnamed: 0                             37461 non-null  int64
 1   go_primary_key                         37460 non-null  float64
 2   council_district                       37205 non-null  float64
 3   go_highest_offense_desc                37461 non-null  object
 4   highest_nibrs_ucr_offense_description  37461 non-null  object
 5   go_report_date                         37461 non-null  object
 6   go_location                            36702 non-null  object
 7   clearance_status                       35742 non-null  object
 8   clearance_date                         35742 non-null  object
 9   go_district                            37461 non-null  object
 10  go_location_zip                        37294 non-null  float64
 11  go_census_tract                        37294 non-null  float64
 12  go_x_coordinate                        36594 non-null  float64
 13  go_y_coordinate                        36594 non-null  float64
dtypes: float64(6), int64(1), object(7)
memory usage: 3.0+ MB

In [222]:
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35097 entries, 0 to 35096
Data columns (total 14 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Unnamed: 0                             35097 non-null  int64
 1   go_primary_key                         35095 non-null  float64
 2   council_district                       34844 non-null  float64
 3   go_highest_offense_desc                35097 non-null  object
 4   highest_nibrs_ucr_offense_description  35097 non-null  object
 5   go_report_date                         35097 non-null  object
 6   go_location                            34286 non-null  object
 7   clearance_status                       32667 non-null  object
 8   clearance_date                         32665 non-null  object
 9   go_district                            35097 non-null  object
 10  go_location_zip                        34982 non-null  float64
 11  go_census_tract                        34982 non-null  float64
 12  go_x_coordinate                        34231 non-null  float64
 13  go_y_coordinate                        34231 non-null  float64
dtypes: float64(6), int64(1), object(7)
memory usage: 2.8+ MB

In [223]:
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37156 entries, 0 to 37155
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                37156 non-null  int64
 1   go_primary_key_year_plus  37156 non-null  int64
 2   council_district          36895 non-null  float64
 3   go_highest_offense_desc   37156 non-null  object
 4   crime_type                37156 non-null  object
 5   go_report_date            37156 non-null  object
 6   go_location               36352 non-null  object
 7   go_x_coordinate           36271 non-null  float64
 8   go_y_coordinate           36271 non-null  float64
 9   clearance_status          35702 non-null  object
 10  clearance_date            35702 non-null  object
 11  go_district               37156 non-null  object
 12  go_location_zip           36989 non-null  float64
 13  go_census_tract           36989 non-null  float64
dtypes: float64(5), int64(2), object(7)
memory usage: 3.0+ MB

In [224]:
# fixing columns names 

df_2015.drop("Unnamed: 0", axis=1, inplace = True)
df_2016.drop("Unnamed: 0", axis=1, inplace = True)
df_2017.drop("Unnamed: 0", axis=1, inplace = True)
df_2018.drop("Unnamed: 0", axis=1, inplace = True)

In [225]:
df_2017.head()

,go_primary_key,council_district,go_highest_offense_desc,highest_nibrs_ucr_offense_description,go_report_date,go_location,clearance_status,clearance_date,go_district,go_location_zip,go_census_tract,go_x_coordinate,go_y_coordinate
0,2.017340e+09,1.0,AUTO THEFT,Auto Theft,3-Feb-17,6200 LOYOLA LN ...,N,10-Feb-17,C,78724.0,22.02,3143028.0,10083917.0
1,2.017560e+09,9.0,AGG ASSAULT,Agg Assault,25-Feb-17,300 E 6TH ST ...,C,25-Feb-17,G,78701.0,11.00,3115154.0,10070604.0
2,2.017501e+10,7.0,BURGLARY OF VEHICLE,Theft,12-Feb-17,13609 N IH 35 NB ...,N,13-Feb-17,E,78753.0,18.39,3135452.0,10127757.0
3,2.017501e+10,4.0,BURGLARY OF VEHICLE,Theft,22-Feb-17,1030 NORWOOD PARK BLVD ...,N,23-Feb-17,I,78753.0,18.13,3129996.0,10096983.0
4,2.017501e+10,2.0,THEFT,Theft,8-Mar-17,6231 E STASSNEY LN ...,N,9-Mar-17,F,78744.0,24.31,3121692.0,10046564.0

In [226]:
# let's check columns meaning

In [227]:
guid = pd.read_csv("GUIDE_-_Annual_Crime.csv")

In [228]:
guid

,Data purpose:,(none)
0,This Annual Crime dataset provides the raw dat...,NaN
1,Corresponding data:,NaN
2,This guide corresponds to the Annual Crime dat...,NaN
3,https://data.austintexas.gov/browse?Additional...,NaN
4,Note: The official crime counts used to produc...,NaN
5,Corresponding report:,NaN
6,The Annual Crime and Traffic Report is posted ...,NaN
7,http://www.austintexas.gov/page/annual-crime-t...,NaN
8,Field definitions:,NaN
9,Below are the fields and definitions contained...,NaN
10,Field Name,Definition
11,GO Primary Key,Case number
12,Council District,Austin city council district where the inciden...
13,GO Highest Offense Desc,The crime committed
14,Highest NIBRS/UCR Offense Description,The FBI category for the crime committed
15,GO Report Date,Date the incident was reported
16,GO Location,Location of incident (rape locations are exclu...
17,Clearance Status,Codes used to identify if a crime was solved (...
18,Clearance Date,Date the crime was solved
19,GO District,APD Sector where the incident occurred (see lo...
20,GO Location Zip,Incident zip code
21,GO Census Tract,Incident census tract
22,GO X Coordinate,Incident location using projection NAD 1983 St...
23,GO Y Coordinate,NaN
24,Field lookups,NaN
25,Clearance Status,NaN
26,C,Cleared by Arrest
27,O,Cleared by Exception
28,N,Not cleared
29,GO District,NaN
30,A,Adam
31,AP,Airport
32,B,Baker
33,C,Charlie
34,D,David
35,E,Edward
36,F,Frank
37,G,George
38,H,Henry
39,I,Ida
40,UK,Unknown

### Field Name	Definition
- GO Primary Key	Case number => case_number  should be object 
- Council District	Austin city council district where the incident occurred
- GO Highest Offense Desc	The crime committed => crime describtion 
- Highest NIBRS/UCR Offense Description	The FBI category for the crime committed => crime type 
- GO Report Date	Date the incident was reported
- GO Location	Location of incident (rape locations are excluded to protect victims)
- Clearance Status	Codes used to identify if a crime was solved (see lookup table below)
- Clearance Date	Date the crime was solved
- GO District	APD Sector where the incident occurred (see lookup table below)
- GO Location Zip	Incident zip code
- GO Census Tract	Incident census tract
- GO X Coordinate	Incident location using projection NAD 1983 State Plane Texas Central FIPS 4203 (US Feet)
- GO Y Coordinate

- lookup table 
- Clearance Status	
  C 	 Cleared by Arrest
  O	     Cleared by Exception
  N	     Not cleared
- GO District	
  A	    Adam
  AP    Airport
  B	    Baker
  C	    Charlie
  D	    David
  E	    Edward
  F	    Frank
  G	    George
  H	    Henry
  I	    Ida
  UK    Unknown

In [229]:
def change_col_name(df, column, new_name):
    
    df.rename(columns={column : new_name}, inplace=True)

In [230]:
change_col_name(df_2015, "go_primary_key", "case_number")
change_col_name(df_2016, "go_primary_key", "case_number")
change_col_name(df_2017, "go_primary_key", "case_number")
change_col_name(df_2018, "go_primary_key_year_plus", "case_number")

In [241]:
change_col_name(df_2018, "go_highest_offense_desc", "crime_desc")
change_col_name(df_2017, "go_highest_offense_desc", "crime_desc")
change_col_name(df_2016, "go_highest_offense_desc", "crime_desc")
change_col_name(df_2015, "go_highest_offense_desc", "crime_desc")

change_col_name(df_2017, "highest_nibrs_ucr_offense_description", "crime_type")
change_col_name(df_2016, "highest_nibrs_ucr_offense_description", "crime_type")
change_col_name(df_2015, "highest_nibrs_ucr_offense_description", "crime_type")

In [242]:
df_2018.columns == df_2015.columns

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False])

In [247]:
# fix column order so they all match 
df_2018 = df_2018[['case_number',
 'council_district',
 'crime_desc',
 'crime_type',
 'go_report_date',
 'go_location',
 'clearance_status',
 'clearance_date',
 'go_district',
 'go_location_zip',
 'go_census_tract',
 'go_x_coordinate',
 'go_y_coordinate']]

In [248]:
df_2018.columns == df_2015.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [257]:
# concat the data 
df = pd.concat([df_2018, df_2017, df_2016, df_2015], axis = 0)

In [258]:
df.shape

(148287, 13)

In [259]:
df.head()

,case_number,council_district,crime_desc,crime_type,go_report_date,go_location,clearance_status,clearance_date,go_district,go_location_zip,go_census_tract,go_x_coordinate,go_y_coordinate
0,2.018344e+10,9.0,AUTO THEFT,Auto Theft,10-Dec-18,2902 HAMPTON RD,N,19-Dec-18,B,78705.0,4.01,3118304.0,10078620.0
1,2.018504e+10,9.0,THEFT BY SHOPLIFTING,Theft,16-Oct-18,1201 BARBARA JORDAN BLVD,N,17-Oct-18,B,78723.0,3.06,3124601.0,10084923.0
2,2.018800e+10,10.0,BURGLARY OF VEHICLE,Theft,22-Jun-18,2600 LAKE AUSTIN BLVD,N,27-Jun-18,B,78703.0,16.02,3104471.0,10074894.0
3,2.018186e+10,4.0,BURGLARY OF RESIDENCE,Burglary,5-Jul-18,5330 N IH 35 SVRD SB,N,13-Sep-18,I,78751.0,21.05,3124538.0,10087177.0
4,2.018504e+10,7.0,BURGLARY OF VEHICLE,Theft,24-Sep-18,12802 POWDERHORN ST,N,24-Sep-18,A,78727.0,18.47,3129160.0,10126575.0